### ISSUE TITLE
Fejl når jeg downloader afleveringer

### ISSUE THREAD

**Issue by BarrensZeppelin** [Mortal/bbfetch#12]
Jeg får følgende fejl, når jeg forsøger at downloade de studerendes afleveringer:
```
[2020-02-06 09:39:33,521 INFO] Sending login details to WAYF
[2020-02-06 09:39:34,809 INFO] Refresh gradebook
[2020-02-06 09:39:34,886 INFO] Fetching student group memberships
[2020-02-06 09:39:35,916 DEBUG] Switch to edit mode
[2020-02-06 09:39:38,974 DEBUG] Fetching datatable took 4.1 s
[2020-02-06 09:39:38,990 INFO] Refresh gradebook
[2020-02-06 09:39:39,056 INFO] Fetching 224 attempt lists
[2020-02-06 09:39:40,681 INFO] Fetch details for attempt Group Attempt Gruppe 1 - 15 05/02/20
[2020-02-06 09:39:42,276 ERROR] Uncaught exception
Traceback (most recent call last):
  File "/home/zii/repos/bbfetch/blackboard/grading.py", line 809, in execute_from_command_line
    grading.main(args, session, grading)
  File "/home/zii/repos/bbfetch/blackboard/grading.py", line 655, in main
    visible=True, needs_grading=True)
  File "/home/zii/repos/bbfetch/blackboard/grading.py", line 338, in download_all_attempt_files
    self.download_attempt_files(attempt)
  File "/home/zii/repos/bbfetch/blackboard/grading.py", line 393, in download_attempt_files
    files = self.get_attempt_files(attempt)
  File "/home/zii/repos/bbfetch/blackboard/grading.py", line 473, in get_attempt_files
    rubrics = self.get_rubrics(attempt)
  File "/home/zii/repos/bbfetch/blackboard/grading.py", line 105, in get_rubrics
    return [self.get_rubric(attempt_rubric) for attempt_rubric in rubrics]
  File "/home/zii/repos/bbfetch/blackboard/grading.py", line 105, in <listcomp>
    return [self.get_rubric(attempt_rubric) for attempt_rubric in rubrics]
  File "/home/zii/repos/bbfetch/blackboard/grading.py", line 72, in get_rubric
    assoc_id = attempt_rubric['assocEntityId']
KeyError: 'assocEntityId'
```
Det er den samme fejl uanset om jeg forsøger at downloade for alle grupper eller kun en enkelt.

`attempt_rubric` består af følgende:
```python
{
  'id': '_2599_1', 
  'title': 'ProgSprog', 
  'client_changed': 'false', 
  'rubricEvalId': None, 
  'feedback': None, 
  'total_value': None,
  'override_value': None,
  'calculated_percent': None,
  'max_value': '3.000000000000000',
  'rows': [
    {'row_id': '_7050_1', 'cell_id': None, 'rubric_cell_eval': None, 'feedback': None, 'selected_percent': None}
  ]
}
```

Jeg kan se listen af grupper og deres submissing vha. `./grading`.

Er der andre der oplever denne fejl (det kan være Blackboard har ændret responsformat), eller er det mere sandsynligt en fejl i min opsætning?

**Comment by Mortal** [comment]
Hmm. Er det vigtigt for dig at kunne bruge rubrics? Hvis ikke, så kan du prøve at tilføje følgende til din grading.py:

```
    def get_rubrics(self, attempt_id):
        return []
```

Det er ikke mit indtryk at rubrics er mega gennemtestet i bbfetch, men jeg skal ikke kunne sige om nogen har brugt det med succes.

**Comment by BarrensZeppelin** [comment]
Det virker umiddelbart at override `get_rubrics`. :+1: 

Hvis jeg forsøger at downloade afleveringer jeg allerede har gradet får jeg:
```
[2020-02-07 12:44:32,046 INFO] Refresh gradebook
[2020-02-07 12:44:32,338 INFO] Fetch details for attempt Group Attempt Gruppe DA3 - 02 05/02/20
[2020-02-07 12:44:34,130 ERROR] Parsing error
No download link for file 'ProgSprog.pdf'
ParserError logged to 2020-02-07_1244_parseerror.txt
```

Det virker til at bbfetch muligvis er forvirret over, at jeg har annoteret PDF'en via. blackboard.
Download-linket er i hvert fald stadig i HTML'en:
```html
...
<ul id="cmul0_2f98cea4bf404873bd0522a414c751c3"> 
    <li class="contextmenubar_top">
      <a href="#close" class="close-menu">
        <span class="close-contextmenu" data-icon="X" role="presentation" aria-hidden="true"></span>
        <img alt="Close Menu" src="/images/ci/ng/close_mini.gif"></a>
    </li>      
              <li id="file_download_0_2f98cea4bf404873bd0522a414c751c3"><a href="/webapps/assignment/download?group=true&course_id=_133813_1&attempt_id=_xxxxxx_1&file_id=_xxxxx_1&fileName=Miniscala1_Afl.pdf" id="file_download_0_2f98cea4bf404873bd0522a414c751c3"   title="Download Original File"     >Download Original File</a></li>
                   <li id="file_download_with_annotations_0_2f98cea4bf404873bd0522a414c751c3"><a href="javascript:void(0);" id="file_download_with_annotations_0_2f98cea4bf404873bd0522a414c751c3" onclick="gradeAssignment.downloadInfo( event, '_110136_1', true );"  title="Download Annotated PDF"     >Download Annotated PDF</a></li>
            </ul>
...
```
